### ISSUE TITLE
引用的时候语法错误？static displayName= "xxxx"

### ISSUE THREAD

**Issue by sukui** [Lobos/react-ui#4]
ERROR in ./~/rctui/src/js/components/checkbox.jsx
Module build failed: SyntaxError: ~/work/test/react-test/node_modules/rctui/src/js/components/checkbox.jsx: Unexpected token (8:21)
   6 | 
   7 | class Checkbox extends React.Component {
>  8 |   static displayName = "Checkbox"
     |                      ^
   9 | 
  10 |   static propTypes = {
11 |     checked: React.PropTypes.bool,
    at Parser.pp.raise (/Users/sukui/work/test/react-test/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/Users/sukui/work/test/react-test/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:82:8)

貌似不支持static 关键字 ？

**Comment by Lobos** [comment]
static 是 es7 的，webpack 里面要指定stage， babel-loader?stage=0

**Comment by sukui** [comment]
不好意思. 忘记关闭了.

**Comment by sukui** [comment]
谢谢了
